// crawler/juejin-crawler.mjs
import { chromium } from '@playwright/test';
import fs from 'fs';
import path from 'path';

async function scrapeJuejinFrontend() {
  const browser = await chromium.launch({
    headless: false,
    slowMo: 300,
    args: ['--start-maximized', '--disable-gpu', '--no-sandbox'],
  });

  const context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  });

  const page = await context.newPage();

  console.log('🌐 正在打开掘金前端版块...');
  await page.goto('https://juejin.cn/frontend', {
    waitUntil: 'load',
    timeout: 60000,
  });

  console.log('⏳ 等待页面加载完成...');
  await page.waitForTimeout(3000);

  try {
    await page.waitForSelector('.article-list', { timeout: 15000 });
    console.log('📡 正在抓取文章列表...');
  } catch {
    console.log('🔄 尝试其他选择器...');
    await page.waitForSelector('.list-container', { timeout: 15000 });
  }

  const articles = await page.evaluate(() => {
    const results = [];
    
    const items = document.querySelectorAll('.article-item, .item, article');
    
    items.forEach((item) => {
      const titleEl = item.querySelector('h3 a, .title a, .article-title a');
      const authorEl = item.querySelector('.author-name, .user-name, .username a');
      const likesEl = item.querySelector('.like-count, .action-item.like, .article-like');
      const summaryEl = item.querySelector('.article-desc, .abstract, .desc');

      if (titleEl) {
        const parseNumber = (text) => {
          if (!text) return 0;
          const match = text.match(/[\d.]+/);
          const num = match ? parseFloat(match[0]) : 0;
          if (text.includes('k') || text.includes('K')) return num * 1000;
          if (text.includes('w') || text.includes('W')) return num * 10000;
          return num;
        };

        const title = titleEl.textContent?.trim() || '';
        if (title.length > 5) {
          results.push({
            title: title,
            author: authorEl?.textContent?.trim() || '未知作者',
            likes: parseNumber(likesEl?.textContent?.trim()),
            summary: summaryEl?.textContent?.trim() || '',
            url: titleEl.getAttribute('href') || '',
          });
        }
      }
    });

    return results;
  });

  console.log(`✅ 共抓取到 ${articles.length} 篇文章`);

  await browser.close();

  return articles.sort((a, b) => b.likes - a.likes).slice(0, 10);
}

function generateReport(articles) {
  const now = new Date();
  const dateStr = now.toLocaleDateString('zh-CN');

  let report = `# 🔥 掘金前端热门文章分析报告\n\n`;
  report += `> **生成时间**: ${dateStr}\n`;
  report += `> **数据来源**: [掘金前端版块](https://juejin.cn/frontend)\n`;
  report += `> **统计范围**: 今日点赞量 TOP 10 文章\n\n`;
  report += `---\n\n`;

  report += `## 📊 今日热门文章 TOP 10\n\n`;
  report += `| 排名 | 标题 | 作者 | 点赞数 |\n`;
  report += `|:---:|:---|:---|:---:|\n`;

  articles.forEach((article, index) => {
    const rank = ['🏆', '🥈', '🥉', '4', '5', '6', '7', '8', '9', '10'][index];
    const url = article.url.startsWith('http') ? article.url : `https://juejin.cn${article.url}`;
    report += `| ${rank} | [${article.title}](${url}) | ${article.author} | ${article.likes.toLocaleString()} |\n`;
  });

  report += `\n---\n\n`;
  report += `## 📋 文章摘要速览\n\n`;

  articles.forEach((article, index) => {
    report += `### ${index + 1}. ${article.title}\n`;
    report += `- **作者**: ${article.author}\n`;
    const summary = article.summary || '暂无摘要';
    report += `- **摘要**: ${summary.slice(0, 150)}${summary.length > 150 ? '...' : ''}\n\n`;
  });

  report += `---\n\n`;
  report += `## 🎯 技术趋势分析\n\n`;

  const keywords = {};
  articles.forEach((article) => {
    const text = `${article.title} ${article.summary}`;
    const techKeywords = [
      'AI', 'Vue', 'React', 'CSS', 'JavaScript', 'TypeScript',
      '性能', '全栈', '面试', '算法', '响应式', 'Node.js',
      '前端', '开发', '框架', 'API', '代码', '优化', '工程',
      'Playwright', '爬虫', '自动化', '测试'
    ];

    techKeywords.forEach((kw) => {
      if (text.includes(kw)) {
        keywords[kw] = (keywords[kw] || 0) + 1;
      }
    });
  });

  const sortedKeywords = Object.entries(keywords).sort((a, b) => b[1] - a[1]);

  report += `### 当前热门技术关键词\n\n`;
  report += `| 关键词 | 出现次数 |\n`;
  report += `|--------|----------|\n`;
  sortedKeywords.forEach(([kw, count]) => {
    report += `| ${kw} | ${count} |\n`;
  });

  report += `\n### 趋势洞察\n\n`;
  report += `- **AI 相关**: AI 编程、AI 工具是当前最热门的话题\n`;
  report += `- **工程实践**: 代码质量、性能优化持续受到关注\n`;
  report += `- **职业发展**: 全栈 vs 专精、面试经验等职业话题热度高\n`;
  report += `- **基础技能**: CSS、算法、响应式布局仍是核心关注点\n\n`;

  report += `---\n\n`;
  report += `> 📝 **报告说明**: 本报告基于掘金前端版块实时数据生成\n\n`;
  report += `**Generated by Playwright Crawler** ✨\n`;

  return report;
}

async function main() {
  console.log('🚀 开始抓取掘金前端热门文章...\n');

  try {
    const articles = await scrapeJuejinFrontend();

    console.log('\n📊 抓取结果:');
    articles.forEach((article, index) => {
      console.log(`${index + 1}. ${article.title} - ${article.author} (${article.likes.toLocaleString()} 赞)`);
    });

    if (articles.length === 0) {
      console.log('⚠️ 未抓取到文章，可能需要更新选择器');
      return;
    }

    const report = generateReport(articles);
    const desktopPath = path.join(process.env.USERPROFILE || '', 'Desktop', '掘金前端热门分析报告.md');
    
    fs.writeFileSync(desktopPath, report, 'utf-8');
    console.log(`\n✅ 报告已保存到: ${desktopPath}`);
  } catch (error) {
    console.error('❌ 抓取失败:', error.message);
  }
}

main();