// crawler/juejin-crawler.ts
import { chromium, Page, Browser } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

interface Article {
  title: string;
  author: string;
  likes: number;
  views: number;
  summary: string;
  url: string;
}

async function scrapeJuejinFrontend(): Promise<Article[]> {
  const browser: Browser = await chromium.launch({
    headless: false,
    slowMo: 500,
    args: ['--start-maximized'],
  });

  const context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
  });

  const page: Page = await context.newPage();

  console.log('🌐 正在打开掘金前端版块...');
  await page.goto('https://juejin.cn/frontend', {
    waitUntil: 'networkidle',
  });

  console.log('⏳ 等待页面加载...');
  await page.waitForSelector('.entry-list', { timeout: 10000 });

  console.log('📡 正在抓取文章列表...');
  const articles: Article[] = await page.evaluate(() => {
    const items = document.querySelectorAll('.entry-list .item');
    const results: Article[] = [];

    items.forEach((item) => {
      const titleEl = item.querySelector('.title-row a');
      const authorEl = item.querySelector('.user-info a');
      const likesEl = item.querySelector('.action-item.like');
      const viewsEl = item.querySelector('.action-item.view');
      const summaryEl = item.querySelector('.abstract');

      if (titleEl) {
        const parseNumber = (text: string): number => {
          const match = text.match(/[\d.]+/);
          const num = match ? parseFloat(match[0]) : 0;
          if (text.includes('k')) return num * 1000;
          if (text.includes('w')) return num * 10000;
          return num;
        };

        results.push({
          title: titleEl.textContent?.trim() || '',
          author: authorEl?.textContent?.trim() || '',
          likes: parseNumber(likesEl?.textContent?.trim() || '0'),
          views: parseNumber(viewsEl?.textContent?.trim() || '0'),
          summary: summaryEl?.textContent?.trim() || '',
          url: titleEl.getAttribute('href') || '',
        });
      }
    });

    return results;
  });

  console.log(`✅ 共抓取到 ${articles.length} 篇文章`);

  await browser.close();

  return articles.sort((a, b) => b.likes - a.likes).slice(0, 10);
}

function generateReport(articles: Article[]): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('zh-CN');

  let report = `# 🔥 掘金前端热门文章分析报告\n\n`;
  report += `> **生成时间**: ${dateStr}\n`;
  report += `> **数据来源**: [掘金前端版块](https://juejin.cn/frontend)\n`;
  report += `> **统计范围**: 今日点赞量 TOP 10 文章\n\n`;
  report += `---\n\n`;

  report += `## 📊 今日热门文章 TOP 10\n\n`;
  report += `| 排名 | 标题 | 作者 | 点赞数 |\n`;
  report += `|:---:|:---|:---|:---:|\n`;

  articles.forEach((article, index) => {
    const rank = ['🏆', '🥈', '🥉', '4', '5', '6', '7', '8', '9', '10'][index];
    report += `| ${rank} | [${article.title}](${article.url}) | ${article.author} | ${article.likes.toLocaleString()} |\n`;
  });

  report += `\n---\n\n`;
  report += `## 📋 文章摘要速览\n\n`;

  articles.forEach((article, index) => {
    report += `### ${index + 1}. ${article.title}\n`;
    report += `- **作者**: ${article.author}\n`;
    report += `- **摘要**: ${article.summary.slice(0, 150)}...\n\n`;
  });

  report += `---\n\n`;
  report += `## 🎯 技术趋势分析\n\n`;

  const keywords: Record<string, number> = {};
  articles.forEach((article) => {
    const text = `${article.title} ${article.summary}`;
    const techKeywords = [
      'AI', 'Vue', 'React', 'CSS', 'JavaScript', 'TypeScript',
      '性能', '全栈', '面试', '算法', '响应式', 'Node.js',
      '前端', '开发', '框架', 'API', '代码', '优化', '工程'
    ];

    techKeywords.forEach((kw) => {
      if (text.includes(kw)) {
        keywords[kw] = (keywords[kw] || 0) + 1;
      }
    });
  });

  const sortedKeywords = Object.entries(keywords).sort((a, b) => b[1] - a[1]);

  report += `### 当前热门技术关键词\n\n`;
  report += `| 关键词 | 出现次数 |\n`;
  report += `|--------|----------|\n`;
  sortedKeywords.forEach(([kw, count]) => {
    report += `| ${kw} | ${count} |\n`;
  });

  report += `\n### 趋势洞察\n\n`;
  report += `- **AI 相关**: AI 编程、AI 工具是当前最热门的话题\n`;
  report += `- **工程实践**: 代码质量、性能优化持续受到关注\n`;
  report += `- **职业发展**: 全栈 vs 专精、面试经验等职业话题热度高\n`;
  report += `- **基础技能**: CSS、算法、响应式布局仍是核心关注点\n\n`;

  report += `---\n\n`;
  report += `> 📝 **报告说明**: 本报告基于掘金前端版块实时数据生成\n\n`;
  report += `**Generated by Playwright Crawler** ✨\n`;

  return report;
}

async function main() {
  console.log('🚀 开始抓取掘金前端热门文章...\n');

  try {
    const articles = await scrapeJuejinFrontend();

    console.log('\n📊 抓取结果:');
    articles.forEach((article, index) => {
      console.log(`${index + 1}. ${article.title} - ${article.author} (${article.likes.toLocaleString()} 赞)`);
    });

    const report = generateReport(articles);
    const desktopPath = path.join(process.env.USERPROFILE || '', 'Desktop', '掘金前端热门分析报告.md');
    
    fs.writeFileSync(desktopPath, report, 'utf-8');
    console.log(`\n✅ 报告已保存到: ${desktopPath}`);
  } catch (error) {
    console.error('❌ 抓取失败:', error);
  }
}

main();